name: saints_flutter_1_22
description: Lives of saints
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.9.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.0
  intl: any
  rxdart: ^0.18.1
  shared_preferences: any
  sqflite: ^1.1.7+3
  path_provider: ^1.4.4
  html2md:
  image: "^2.0.4"
  async: "^2.0.7"
  launch_review: "^1.0.1"
  flutter_launcher_icons:
  esys_flutter_share: ^1.0.2
  path: ^1.6.4
  supercharged: ^1.6.0
  fluttertoast: ^7.1.6
  gallery_saver: ^2.0.1
  in_app_purchase: ^0.3.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/saints_icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - images/
    - icons/
